### ISSUE TITLE
Ergodox Case

### ISSUE THREAD

**Issue by tekamolo** [jjt/jjt.github.io#7]
I saw an ergodox case on google and it led me to your ergodox article review:
![8943930400_c2e1f0b47e_z](https://cloud.githubusercontent.com/assets/1892789/6831982/ecdbda02-d323-11e4-9c50-2191c48df6e4.jpg)

I would like to know where did you get this image? how did you build this if it is yours.

If that is not the case which "ergodox case" do you use and how did you get it? Do you know how to build the case yourself?

cheers

**Comment by jjt** [comment]
@tekamolo That is not my case unfortunately. It's beautiful though!
